### ISSUE TITLE
ERROR spawn /bin/sh ENOENT Error: spawn /bin/sh ENOENT  on Windows 10

### ISSUE THREAD

**Issue by suthivich** [kengz/spacy-nlp#27]
ERROR spawn /bin/sh ENOENT Error: spawn /bin/sh ENOENT  
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by acenturyandabit** [comment]
this is not designed for windows. im working on a similar lib for win.

**Comment by acenturyandabit** [comment]
https://github.com/acenturyandabit/spacy-node-win

good luck
